name: OmnipotentialChests
version: ${project.version}
main: wg.omnipotentialchests.chests.omnipotentialchests.OmnipotentialChests
description: Plugin that allows you to creating chests with random rewards
commands:
  omnichests:
    usage: omnichests
    description: main commands for OmnipotentialChests
    permission: omnipotentialchests.commands.omnichests
    aliases:
      - chests
      - omchests
